import os
import dotenv
import logging
import re
import sys
from typing import List, Dict, Optional
import supabase
import requests
from requests.exceptions import RequestException

# Configuração do logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('app.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# Carrega as variáveis de ambiente
dotenv.load_dotenv()

# Configuração do Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Configuração do Z-API
ZAPI_INSTANCE_ID = os.getenv("ZAPI_INSTANCE_ID")
ZAPI_TOKEN = os.getenv("ZAPI_TOKEN")
ZAPI_URL = f"https://api.z-api.io/instances/{ZAPI_INSTANCE_ID}/token/{ZAPI_TOKEN}/send-text"


def validar_variaveis_ambiente() -> bool:
    """Valida se todas as variáveis de ambiente estão configuradas"""
    if not all([SUPABASE_URL, SUPABASE_KEY, ZAPI_INSTANCE_ID, ZAPI_TOKEN]):
        logger.error("Variáveis de ambiente não configuradas corretamente.")
        logger.error("Por favor, configure o arquivo .env com as credenciais.")
        return False
    return True


def validar_numero_telefone(numero: str) -> bool:
    """Valida se o número de telefone tem pelo menos 10 dígitos"""
    # Remove todos os caracteres não numéricos
    numero_limpo = re.sub(r'\D', '', numero)
    return len(numero_limpo) >= 10


def criar_tabela_contatos(supabase_client):
    """Cria a tabela contatos no Supabase, caso não exista"""
    try:
        # Tenta consultar a tabela para verificar se existe
        supabase_client.table('contatos').select('id').limit(1).execute()
        logger.info("Tabela 'contatos' já existe no Supabase.")
        return True
    except Exception as e:
        # Se não existe, exibe mensagem para o usuário criar manualmente
        logger.warning("Tabela 'contatos' não encontrada.")
        logger.warning("Por favor, crie a tabela manualmente no Supabase SQL Editor com o seguinte comando:")
        logger.warning("""
        create table contatos (
            id bigint generated by default as identity primary key,
            nome text not null,
            numero text not null,
            status text default 'pendente'
        );
        """)
        return False


def buscar_contatos_pendentes(supabase_client) -> List[Dict]:
    """Busca todos os contatos com status 'pendente'"""
    try:
        contatos_response = supabase_client.table('contatos').select('*').eq('status', 'pendente').execute()
        return contatos_response.data
    except Exception as e:
        logger.error(f"Erro ao buscar contatos pendentes: {str(e)}")
        raise


def enviar_mensagem_zapi(nome: str, numero: str) -> bool:
    """Envia uma mensagem personalizada para um número via Z-API"""
    mensagem = f"Olá, {nome} tudo bem com você?"
    payload = {
        "phone": numero,
        "message": mensagem
    }
    try:
        response = requests.post(ZAPI_URL, json=payload, timeout=10)
        response.raise_for_status()  # Levanta erro para status >= 400
        return True
    except RequestException as e:
        logger.error(f"Erro ao enviar mensagem para {numero}: {str(e)}")
        return False


def atualizar_status_contato(supabase_client, contato_id: int, status: str) -> None:
    """Atualiza o status de um contato no Supabase"""
    try:
        supabase_client.table('contatos').update({'status': status}).eq('id', contato_id).execute()
        logger.info(f"Status do contato ID {contato_id} atualizado para '{status}'.")
    except Exception as e:
        logger.error(f"Erro ao atualizar status do contato ID {contato_id}: {str(e)}")


def resetar_contatos_pendentes(supabase_client) -> None:
    """Reseta todos os contatos para status 'pendente'"""
    try:
        response = supabase_client.table('contatos').update({'status': 'pendente'}).neq('id', 0).execute()
        logger.info(f"Resetados {len(response.data)} contatos para status 'pendente'.")
    except Exception as e:
        logger.error(f"Erro ao resetar contatos: {str(e)}")


def main():
    """Função principal do programa"""
    # Verifica se o usuário quer resetar os contatos
    if len(sys.argv) > 1 and sys.argv[1] == 'reset':
        if not validar_variaveis_ambiente():
            return
        try:
            supabase_client = supabase.create_client(SUPABASE_URL, SUPABASE_KEY)
            resetar_contatos_pendentes(supabase_client)
        except Exception as e:
            logger.error(f"Ocorreu um erro ao resetar contatos: {str(e)}")
        return

    # Fluxo principal para enviar mensagens
    if not validar_variaveis_ambiente():
        return

    try:
        supabase_client = supabase.create_client(SUPABASE_URL, SUPABASE_KEY)

        # Verifica se a tabela existe
        if not criar_tabela_contatos(supabase_client):
            return

        # Busca contatos pendentes
        contatos = buscar_contatos_pendentes(supabase_client)
        
        if not contatos:
            logger.info("Nenhum contato pendente encontrado no Supabase.")
            logger.info("Verifique se as políticas de RLS estão configuradas corretamente para permitir leitura.")
            return

        logger.info(f"Encontrados {len(contatos)} contatos pendentes para enviar mensagens.")
        
        # Limita a 3 contatos conforme o desafio
        contatos_para_enviar = contatos[:3]
        logger.info(f"Enviando mensagens para {len(contatos_para_enviar)} contatos (limite de 3).")

        for contato in contatos_para_enviar:
            contato_id = contato.get('id')
            nome = contato.get('nome')
            numero = contato.get('numero')
            status = contato.get('status')

            # Validação básica dos dados do contato
            if not nome or not numero or status != 'pendente':
                logger.warning(f"Contato com dados incompletos ou já processado: {contato}")
                continue

            if not validar_numero_telefone(numero):
                logger.warning(f"Número de telefone inválido para contato {nome}: {numero}")
                atualizar_status_contato(supabase_client, contato_id, 'erro')
                continue

            # Envia a mensagem
            sucesso = enviar_mensagem_zapi(nome, numero)

            # Atualiza o status conforme resultado
            if sucesso:
                logger.info(f"Mensagem enviada para {numero} com sucesso!")
                atualizar_status_contato(supabase_client, contato_id, 'enviado')
            else:
                atualizar_status_contato(supabase_client, contato_id, 'erro')

    except Exception as e:
        logger.error(f"Ocorreu um erro inesperado: {str(e)}", exc_info=True)


if __name__ == "__main__":
    main()
